"""Hotspot collection domain contracts."""

from .clustering import (
    CandidateDecision,
    ClusterCandidate,
    ClusteringBatch,
    ClusteringStatus,
    ClusterInputItem,
    EventCluster,
    EventMember,
    SemanticStatus,
)
from .models import (
    CollectionStatus,
    CollectorResult,
    CollectRequest,
    Freshness,
    Platform,
    ProviderAttempt,
    ProviderError,
    ProviderErrorKind,
    ProviderHealth,
    ProviderHealthStatus,
    ProviderHotItem,
    ProviderResult,
    ProviderStatus,
    RawHotItem,
    utc_now,
)
from .normalization import (
    DedupGroup,
    DedupMember,
    NormalizationBatch,
    NormalizationStatus,
    NormalizedHotItem,
    PublishedAtPrecision,
    SnapshotRawItem,
)
from .window import SnapshotWindow, snapshot_window_for

__all__ = [
    "CandidateDecision",
    "ClusterCandidate",
    "ClusterInputItem",
    "ClusteringBatch",
    "ClusteringStatus",
    "CollectRequest",
    "CollectionStatus",
    "CollectorResult",
    "DedupGroup",
    "DedupMember",
    "EventCluster",
    "EventMember",
    "Freshness",
    "NormalizationBatch",
    "NormalizationStatus",
    "NormalizedHotItem",
    "Platform",
    "ProviderAttempt",
    "ProviderError",
    "ProviderErrorKind",
    "ProviderHealth",
    "ProviderHealthStatus",
    "ProviderHotItem",
    "ProviderResult",
    "ProviderStatus",
    "PublishedAtPrecision",
    "RawHotItem",
    "SemanticStatus",
    "SnapshotRawItem",
    "SnapshotWindow",
    "snapshot_window_for",
    "utc_now",
]
